version: '3'
services:
  postgres:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: api_peliculas
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  app:
    environment:
      FLASK_APP: "entrypoint:app"
      FLASK_ENV: "development"
      APP_SETTINGS_MODULE: "config.default"
      variableBD: "postgresql://postgres:password@postgres:5432/api_peliculas"
    
    build: .
    ports:
      - 5000:5000
    volumes: 
      - .:/app
    depends_on:
      - postgres
    command: bash -c "flask db upgrade && flask run --host 0.0.0.0" 
 